In [2]:
import numpy as np
from numpy.linalg import lstsq           #calculate least squares
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

In [11]:
x1 = np.array([6,8,10,14,18]).reshape(5,1)              #first column or first feature
x2 = np.array([2,1,0,2,0]).reshape(5,1)                 #second feature
x0 = np.array([1 for i in range(5)]).reshape(5,1)       #value of x0 is always equal to 1

y = np.array([7,9,13,17.5,18]).reshape(5,1)             #target value 

In [5]:
x = np.concatenate([x0,x1,x2],axis=1)                   #join all the feature set to a single dataset along first axis(columns)
print(x)

[[ 1  6  2]
 [ 1  8  1]
 [ 1 10  0]
 [ 1 14  2]
 [ 1 18  0]]


In [26]:
from numpy import transpose,dot          
from numpy.linalg import inv            #inverse function

eqn_first_half = inv(dot(transpose(x),x))          #(inverse(transpose(x).x))    
eqn_second_half = dot(transpose(x),y)              #(transpose(x).y)
THETA_LS = dot(eqn_first_half,eqn_second_half)     #combining both halves,theta = inverse(transpose(x).x).(transpose(x).y)

print(THETA_LS)                                    #(3,1) matrix because we've three features x0,x1,x2

[[1.1875    ]
 [1.01041667]
 [0.39583333]]


In [33]:
#Alternative method to calculate theta_ls
from numpy.linalg import lstsq            #least squares

theta_ls = lstsq(x,y)[0]
print(theta_ls)

[[1.1875    ]
 [1.01041667]
 [0.39583333]]


/home/abhigith/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  after removing the cwd from sys.path.


In [34]:
#train the model
model = LinearRegression()
model.fit(x,y)              #find the perfect fit line

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [41]:
print(model.intercept_,model.coef_)        #print the parameters calculated by our model

[1.1875] [[0.         1.01041667 0.39583333]]


In [43]:
#test the model
xx1 = np.array([8,9,11,16,12]).reshape(5,1)
xx2 = np.array([2,0,2,2,0]).reshape(5,1)

y_test = np.array([11,8.5,15,18,11]).reshape(5,1)

In [50]:
x_test = np.concatenate([x0,xx1,xx2],axis=1)
predict = model.predict(x_test)

print(predict)

[[10.0625    ]
 [10.28125   ]
 [13.09375   ]
 [18.14583333]
 [13.3125    ]]


In [48]:
model.score(x_test,y_test)

0.7701677731318466